### ISSUE TITLE
User-defined command stopped working.

### ISSUE THREAD

**Issue by AllThisThen** [rowrawer/stream-detector#90]
In 2.8.4 & 2.8.5, just copies %url% value.

**Comment by rowrawer** [comment]
Should be fixed in v2.8.6.

**Comment by keckelt** [comment]
I think the recent changes removed any previously set user defined commands

**Comment by rowrawer** [comment]
That's possible. The code behind that stuff was rewritten due to possible crashing issues so some settings unfortunately might not have gotten carried over for whatever reason.

**Comment by sikkip** [comment]
I still have this problem too (2.8.6) and cannot use any command except Regular URL.

and cannot clear ALL link, cannot collect more link Reset Firefox cannot fix

way to fix is reinstall add-on (I did it 3 times)

[https://youtu.be/7Tin4qv-i_4](url)

**Comment by rowrawer** [comment]
That's some weird stuff. It works just fine for me. Honestly I should probably add a "clear all settings" button in the options for emergencies like this.

**Comment by sikkip** [comment]
it had problem like this about 3 days ago (not sure)
I used this add-on more than 1 month it work very good  

I will roll back to use this Version in my previous issue [https://github.com/rowrawer/stream-detector/issues/86](https://github.com/rowrawer/stream-detector/issues/86l)

**Comment by AllThisThen** [comment]
Don't know about other peoples' experiences. The issue seems resolved to me.
